### ISSUE TITLE
Ensure that system data is read or changed only by the server

### ISSUE THREAD

**Issue by jtazin** [akamel001/Social-Wombat#25]
Phase 4 functionality. There might not be too much to do for this, but we should take care to double-check that this is done properly.

**Comment by akamel001** [comment]
For this issue and the next (#26) we should consider using the security manager as suggested by the TA.

**Comment by plumppapaya** [comment]
We can check for integrity by using a checksum and we can ensure that the contents are only readable by the server via encryption, but I'm not sure if we can prevent anyone from just changing the data bits of our file. SecurityManager won't solve this issue because it only handles permissions within the JVM scope.

**Comment by plumppapaya** [comment]
Done, don't need SecurityManager
